apiVersion: v1
kind: ConfigMap
metadata:
  name: config-wordpress
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: "test"
  WORDPRESS_DB_NAME: test
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-wordpress
data:
  WORDPRESS_DB_PASSWORD: dGVzdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.2.2-apache
          env:
            - name: WORDPRESS_DEBUG
              value: "1"
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-wordpress
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config-wordpress
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-wordpress
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-wordpress
                  key: WORDPRESS_DB_PASSWORD
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
# name: wordpress-ingress
#spec:
# rules:
# - host: "wordpress.io"
#  http:
#   paths:
#    - path: /
#     pathType: Prefix
#    backend:
#     service:
#      name: wordpress-service
#     port:
#      number: 80
