apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # base64 encoded "admin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password"
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4= # base64 encoded "admin"
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ= # base64 encoded "password"
